stages:
  - build
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: "dev"

build_job:
  stage: build
  image: gradle:jdk17
  script:
    - echo "Building application."
    - gradle clean build -x test # Skipping tests for now
  artifacts:
    paths:
      - build/libs/*.jar  # Save the built JAR file for the next stage

deploy_job:
  stage: deploy
  image: openjdk:17
  script:
    - echo "Deploying application."
    - java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar build/libs/×.jar
  environment:
    name: dev
    url: https://microservicespractice.com/product-service