stages:
  - build
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: "dev"

build_job:
  stage: build
  image: gradle:jdk17
  script:
    - echo "Building application."
    - gradle clean build -x test # Skipping tests for now
  artifacts:
    paths:
      - build/libs/*.jar  # Save the built JAR file for the next stage
    expire_in: 1 day

deploy_job:
  stage: deploy
  image: openjdk:17
  script:
    - echo "Deploying application."
    - ls -lh build/libs/
    - nohup java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar build/libs/app.jar > app.log 2>&1 &
    - echo "Application started in the background."
    - echo "URL - https://microservicespractice.com/product-service"
    - curl -f https://microservicespractice.com/product-service/purchase || echo "Products endpoint failed"
  environment:
    name: dev
    url: https://microservicespractice.com/product-service