### GET for non-user
GET http://localhost:8080/product/purchase?productId=1
Content-Type: application/json

### GET for users
GET http://localhost:8080/product/purchase/registered2?productId=1
Content-Type: application/json

### GET test for feign client
GET http://localhost:8080/product/purchase/test?name=registered2
Content-Type: application/json
