spring:
  application:
    name: "fidelity-service"

server:
  port: 8082

mongodb:
  connectionUri: "mongodb://Jaroslav:qwerty@localhost:27017"
  database: "microservicesPractice"
  collection: "fidelity"

